// <auto-generated />
using System;
using FaskeyAtlantic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaskeyAtlantic.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231227172957_SeedEstateToDb")]
    partial class SeedEstateToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaskeyAtlantic.Domain.Entities.Estate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Estates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neatly used 2 bedroom penthouse.  Unit - The unit covers the entire floor, with two massive balconies in front and back, you may decided to add additional rooms in front if you wish but you are not allowed to\r\nadd another floor as the approved amount of floors within the estate is four(4).Content from Nigeria Property Centre",
                            ImageUrl = "https://www.pexels.com/photo/blue-lounger-beside-swimming-pool-221457/",
                            Name = "Banana Ville Resort",
                            Occupancy = 0,
                            Price = 4800.0,
                            Sqft = 1700
                        },
                        new
                        {
                            Id = 2,
                            Description = "Neatly used 3 bedroom. invater - The unit comes with 20-solar panels and 10kva invater - this invater lasts for 12hours and it takes 2 A/cs but all units A/cs are connected to it, you decide which 2 A/cs to leave ON . But\r\nthe light in Osborne Forshore is superb - 23hours and most times it goes for days.Content from Nigeria Property Centre",
                            ImageUrl = "https://www.pexels.com/photo/construction-house-architecture-luxury-53610/",
                            Name = "Exclusive Luxury Mansion",
                            Occupancy = 0,
                            Price = 3800.0,
                            Sqft = 1300
                        },
                        new
                        {
                            Id = 3,
                            Description = "Neatly used 2 bedroom penthouse.  Unit - The unit covers the entire floor, with two massive balconies in front and back, you\r\nmay decided to add additional rooms in front if you wish but you are not allowed to\r\nadd another floor as the approved amount of floors within the estate is four(4).Content from Nigeria Property Centre",
                            ImageUrl = "https://www.pexels.com/photo/white-concrete-2-storey-house-206172/",
                            Name = "Shuqroh Ville",
                            Occupancy = 0,
                            Price = 1400.0,
                            Sqft = 1100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
